# Generated by Django 4.2 on 2024-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_image_user_phone_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
