# Generated by Django 4.2 on 2024-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldcoin',
            name='isage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isemail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isgender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isimage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isintrests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='isphone',
            field=models.BooleanField(default=False),
        ),
    ]
